language: go
go:
  - "1.13.x"
  - "1.12.x"
  - "1.11.x"
  - "1.10.x"
jobs:
  include:
    - stage: test
      script:
        - "cd v3"
        - "go test -v -coverprofile=coverage.txt -covermode=atomic"
        - "bash <(curl -s https://codecov.io/bash)"
